apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: dev-ken-viewer-binding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: ken
    namespace: dev
roleRef:
  kind: Role
  name: namespace-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: namespace-viewer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
# Checking
# kubectl auth can-i list pod --namespace dev --as system:serviceaccount:dev:ken