apiVersion: apps/v1 # Версия API
kind: Deployment # Объект, который создаем
metadata:
  name: web-app # Название Pod
  labels:
    app: web-app # Метки в формате key: value
spec: # Описание Pod
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers: # Описание контейнеров внутри Pod
        - name: frontend-app # Название контейнера
          image: app
          imagePullPolicy: Never
          volumeMounts:
            - name: app
              mountPath: /app
          readinessProbe:
            httpGet:
              port: 8000
              path: /index.html
          livenessProbe:
            tcpSocket:
              port: 8000
      initContainers:
        - name: init-my-service
          image: busybox:1.28
          command: [ 'sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh' ]
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          emptyDir: { }
