apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /data
          name: storage-pod-pvc
  volumes:
    - persistentVolumeClaim:
        claimName: storage-pvc
      name: storage-pod-pvc
