apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pod-viewer
  namespace: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
  namespace: prometheus
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus # Name is case sensitive
roleRef:
  kind: ClusterRole
  name: cluster-pod-viewer
  apiGroup: rbac.authorization.k8s.io

# Checking
# kubectl auth can-i list pod --namespace default --as system:serviceaccount:prometheus:carol