apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: emptyRole
rules:
  - apiGroups: [""]
    resources: [""]
    verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: dave-binding
subjects:
  - kind: ServiceAccount
    name: dave
    namespace: default
roleRef:
  kind: Role
  name: emptyRole
  apiGroup: rbac.authorization.k8s.io

# Проверка
# kubectl auth can-i get pods --namespace default --as system:serviceaccount:default:dave