= Инструкция по установке и настройке кластера

== Установка зависимостей kubespray

[source,bash]
----
$ pip install -r kubespray/requirements.txt
----

== Настроим Terraform переменные для доступа к Yandex Cloud

[source,bash]
----
$ mkdir "terraform"
$ touch terraform/private.auto.tfvars
$ yc config list
$ vim terraform/private.auto.tfvars
$ bash cluster_yc_install.sh
----

После успешного выполнения команд, можем убедиться в сконфигурированном кластере

=== Проверка кластера

[source,bash]
----
$ cat kubespray/inventory/mycluster/artifacts/admin.conf > ~/.kube/config
----

== Конфигурация кластера

Конфигурация происходит из argocd.
Для конфигурации самой argocd нужно вызвать скрипт

[source,bash]
----
$ bash configure_cluster.sh
  # grafana login admin, password prom-operator
  # Подключение к grafana
$ kubectl port-forward svc/obs-stack-grafana 8080:80 -n monitoring
----

Для использование CSI на локальной тачке требуется указание storageClass="local-path"

== Vault

== Kibana

Kibana доступна после создания дашборда

Fixing issue

 error retrieving resource lock ingress-nginx/ingress-controller-leader: leases.coordination.k8s.io "ingress-controller-leader" is forbidden: User "system:serviceaccount:ingress-nginx:ingress-nginx" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "ingress-nginx"

https://github.com/bitnami/charts/issues/11192