= Инструкция по установке и настройке кластера

== Установка зависимостей kubespray

[source,bash]
----
$ pip install -r kubespray/requirements.txt
----

== Настроим Terraform переменные для доступа к Yandex Cloud

[source,bash]
----
$ mkdir "terraform"
$ touch terraform/private.auto.tfvars
$ yc config list
$ vim terraform/private.auto.tfvars
$ bash cluster_yc_install.sh
----

После успешного выполнения команд, можем убедиться в сконфигурированном кластере

=== Проверка кластера

[source,bash]
----
$ cat kubespray/inventory/mycluster/artifacts/admin.conf > ~/.kube/config
----

== Конфигурация кластера

Конфигурация происходит из argocd.
Для конфигурации самой argocd нужно вызвать скрипт

[source,bash]
----
$ bash configure_cluster.sh
  # grafana login admin, password prom-operator
  # Подключение к grafana
$ kubectl port-forward svc/obs-stack-grafana 8080:80 -n monitoring
----

Для использование CSI на локальной тачке требуется указание storageClass="local-path"

== Kibana

Kibana доступна после создания дашборда

Fixing issue

 error retrieving resource lock ingress-nginx/ingress-controller-leader: leases.coordination.k8s.io "ingress-controller-leader" is forbidden: User "system:serviceaccount:ingress-nginx:ingress-nginx" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "ingress-nginx"

https://github.com/bitnami/charts/issues/11192

== Описание интеграции с CI/CD-сервисом

После запуска кластера ci/cd конфигурация подтягивается автоматически

== Подход к организации мониторинга и логирования

Мониторинг реализован на стандартном решении prometheus+Grafana.
Имеются предустановленные дашборды для слежения за состоянием кластера

Для логирования используется EFK стек.
На каждой ноде установлен агент для сбора логов

== Дополнительная информация про вашу платформу

PredProduction Ready платформа Kubernetes.
Почти Cloud Agnostic решение, за исключением Yandex Load Balancer, Terraform, CSI

Имеются необходимые базовые сервисы:

. CI - Gitlab CI
. CD - ArgoCD
. Monitoring - Prometheus+Grafana
. Logging - Elasticsearch, FluentD, Kibana stack
. Tracing - Jaeger
. Secret management - Hashicorp vault
. Config management - Consul
. Registry - Registry
. Ingress - kubespray enabled addon nginx-ingress-controller
. CSI - After cluster installed, will be installed csi(ru.yandex.s3.csi)