---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  namespace: argocd
spec:
  rules:
    - host: argocd.local
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 80
            path: /
            pathType: Prefix
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  description: project for management of Argo CD itself
  # some of my apps within argocd project need to create cluster resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: observability
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: argo
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: artifactory
      server: https://kubernetes.default.svc
    - namespace: infra
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://gitlab.com/otus-hw123/argocd.git
    - https://prometheus-community.github.io/helm-charts
    - https://charts.bitnami.com/bitnami
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://gitlab.com/otus-hw123/argocd.git
    targetRevision: HEAD
    path: infra
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true