apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: frontend-app # Название Pod
  labels:
    label: frontend-app # Метки в формате key: value
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: frontend-app # Название контейнера
      image: frontend-app
      imagePullPolicy: Never
