apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web-app # Название Pod
  labels:
    label: web-app # Метки в формате key: value
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: frontend-app # Название контейнера
      image: frontend-app
      imagePullPolicy: Never
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-my-service
      image: busybox:1.28
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
